spring:
 jpa:
  hibernate: 
   ddl-auto: create-drop
      
 datasource:
  url: jdbc:mysql://localhost:3306/burger_builder
  username: root
  password: Golomt123;
  initialization-mode: always
  platform: mysql
  
server:
  port: 8443
  
userApiUrl: /api/users/**
publicApiUrl: /api/public/**
jwtSecretKey: SecretKeyToGenJWTs
tokePrefix: 
headerString: Authorization
expirationTime: 600_000     